#!/usr/bin/env python3
import colors as c
import random
import battle

# Player's stats

p_health = 100
p_offense = 15
p_defense = 0
    
# Enemies' stats
    
e_health = 20
e_offense = 10
e_defense = 5

# Creates dungeon

w = 5
h = 5

dungeon = [[0 for x in range(w)]for y in range (h)]

# Generates dungeon

x = 4
y = 4

while x > -6:
    while y > -6:
        dungeon[x][y] = random.randrange(0,2)
        y -= 1
    x -= 1
    y = 4

dungeon[0][0] = 0

# Places staircase

while True:
    exit_x = random.randrange(-5,5)
    exit_y = random.randrange(-5,5)
    if exit_x == 0 and exit_y == 0:
        pass
    else:
        dungeon[exit_x][exit_y] = 2    
        break


# Places player

px = 0
py = 0
ptile = dungeon[px][py]

print(c.clear)

print("You find yourself in a dark dungeon.")
print("You think you should try to find a way out.")

while True:
    
    # Choosing a direction
    
    print("In which direction would you like to move?  (Enter n, s, e, or w).")
    direction = input("> ")
    print(c.clear)

    # East

    if direction == "e":
        px += 1
        if px > 4:
            print("You try to move east, but run into a wall.")
            px -= 1
        else:
            ptile = dungeon[px][py]
            if ptile == 1:
                print("You try to move east, but run into a wall.")
                px -= 1
                ptile = dungeon[px][py]
            else:
                print("You move east one tile.")
                battle_chance = random.randrange(0,11)
                if battle_chance == 10:
                    battle.battle(p_health, p_offense, p_defense, e_health, e_offense, e_defense)
    
    # West

    elif direction == "w":
        px -= 1
        if px < -5:
            print("You try to move west, but run into a wall.")
            px += 1
        else:
            ptile = dungeon[px][py]
            if ptile == 1:
                print("You try to move west, but run into a wall.")
                px += 1
                ptile = dungeon[px][py]
            else:
                print("You move west one tile.")
                battle_chance = random.randrange(0,11)
                if battle_chance == 10:
                    battle.battle(p_health, p_offense, p_defense, e_health, e_offense, e_defense)
    
    # North

    elif direction == "n":
        py += 1
        if py > 4:
            print("You try to move north, but run into a wall.")
            py -= 1
        else:
            ptile = dungeon[px][py] 
            if ptile == 1:
                print("You try to move north, but run into a wall.")
                py -= 1
                ptile = dungeon[px][py]
            else:
                print("You move north one tile.")
                battle_chance = random.randrange(0,11)
                if battle_chance == 10:
                    battle.battle(p_health, p_offense, p_defense, e_health, e_offense, e_defense)
    
    # South

    elif direction == "s":
        py -= 1
        if py < -5:
            print("You try to move south, but run into a wall.")
            py += 1
        else:
            ptile = dungeon[px][py]
            if ptile == 1:
                print("You try to move south, but run into a wall.")
                py += 1
                ptile = dungeon[px][py]
            else:
                print("You move south one tile.")
                battle_chance = random.randrange(0,11)
                if battle_chance == 10:
                       battle.battle(p_health, p_offense, p_defense, e_health, e_offense, e_defense)
    
    # Invalid command

    else:
        print("That is not a valid command.")

    # Exit
    
    if ptile == 2:
        print("You find a staircase.")
        print("You ascend the staircase and exit the dungeon.")
        print("A WINNER IS YOU!")
        break

    # Game Over

    if p_health <= 0:
        break
